version: '3.7'

services:
  api_ubs: &ror
    image: ${SERVICE}:${RELEASE}
    ports:
      - 3000:3000
#    image: ${DTR}/${SERVICE}:${RELEASE}
#    deploy:
#      replicas: 2

  sidekiq:
    <<: *ror
    ports: []
#    deploy:
#      replicas: 1