version: '3.7'

services:
  api_ubs: &ror
#    image: ${DTR}/${SERVICE}:${RELEASE}
    image: ${SERVICE}:${RELEASE}
    deploy:
      replicas: ${REPLICAS}

  sidekiq:
    <<: *ror
    deploy:
      replicas: 1